---
- name: set up webserver
  hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: true
